### ISSUE TITLE
The name

### ISSUE THREAD

**Issue by Matesaktesak** [MaximMaximS/TSDB-Legacy#1]
TSDB means Time Series DataBase and using the abbreviation is utterly confusing!

**Comment by MaximMaximS** [comment]
Hello, I am aware of the problem. When I wanted to shorten the name from "TheSimpsonsDatabase", I overlooked that this abbreviation is already in use. But looking at it now,  time series database already clashes with "Technické služby Dolnobřezansko". Unfortunately, it would be financially very expansive to rebrand the project, so we have to

![proxy-image](https://user-images.githubusercontent.com/60849730/216728383-1e4e053f-949d-44a9-b82e-23ffabbb095f.jpg)
